#!/bin/bash
set -e
deno test \
  --allow-read \
  --allow-write \
  --allow-run \
  --allow-net=cdn.skypack.dev \
  --check \
  --doc \
  --jobs \
  --fail-fast
deno check examples/blog/main.ts
deno lint
deno fmt --check --ignore=.vscode/
