on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: deno test --allow-read --allow-write --allow-run --jobs=4
    - run: deno lint
    - run: deno fmt --check --ignore=.vscode/
